#!/usr/bin/env php
<?php
/**
 * @file
 * Small script for random password generation.
 */

// Default value for password length.
$length = 10;

if ($argc > 1) {
    for ($i = 1; $i < $argc; $i++) {
        $option = explode('=', $argv[$i]);
        switch ($option[0]) {
            case '-l':
            case '--length':
                if (isset($option[1])) {
                    $length = $option[1];
                } else {
                    echo 'Wrong option: ' . $argv[$i] . PHP_EOL;
                    exit(1);
                }
            break;

            default:
                if (substr($argv[$i], 0, 1) == '-') {
                    echo 'Unknown option: ' . $argv[$i] . PHP_EOL;
                    exit(1);
                }
            break;
        }
    }
}

if (!is_numeric($length)) {
    echo 'Password length should be a number!' . PHP_EOL;
    exit(1);
}

// This variable contains the list of allowable characters for the
// password. Note that the number 0 and the letter 'O' have been
// removed to avoid confusion between the two. The same is true
// of 'I', 1, and 'l'.
$allowableCharacters = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';

// Zero-based count of characters in the allowable list:
$len = strlen($allowableCharacters) - 1;

// Declare the password as a blank string.
$pass = '';

// Loop the number of times specified by $length.
for ($i = 0; $i < $length; $i++) {
    // Each iteration, pick a random character from the
    // allowable string and append it to the password:
    $pass .= $allowableCharacters[mt_rand(0, $len)];
}

echo $pass . PHP_EOL;
