include ../vars.mk

.PHONY: configure
configure:
	ln -sf $(CURDIR)/gitconfig ~/.gitconfig
	ln -sf $(CURDIR)/gitignore ~/.gitignore
	ln -sf $(CURDIR)/git.sh $(BASH_HOOKS_FOLDER)/git.sh
	ln -sf $(CURDIR)/git.zsh $(ZSH_HOOKS_FOLDER)/git.zsh
