.PHONY: configure
configure:
	ln -sf $(CURDIR)/settings.json ~/Library/Application\ Support/Zed/settings.json
	ln -sf $(CURDIR)/keymap.json ~/Library/Application\ Support/Zed/keymap.json
	ln -sf $(CURDIR)/tasks.json ~/Library/Application\ Support/Zed/tasks.json
	ln -sf $(CURDIR)/snippets ~/Library/Application\ Support/Zed/snippets
	ln -sf $(CURDIR)/themes ~/Library/Application\ Support/Zed/themes
	mkdir -pv ~/Library/Application\ Support/Zed/extensions
	ln -sf $(CURDIR)/extensions/index.json ~/Library/Application\ Support/Zed/extensions/index.json
