.PHONY:all
all: pip npm note

.PHONY: pip
pip:
	sudo -H pip3 install --upgrade \
		mkdocs \
		pygments \
		neovim

.PHONY: npm
npm:
	sudo npm install --global \
		node-static \
		json-server \
		git-open \
		git-recent \
		diff-so-fancy \
		trash-cli
