include ../vars.mk

.PHONY: configure
configure:
	ln -sf $(CURDIR)/opencode.jsonc ~/.config/opencode/opencode.jsonc
	ln -sf $(CURDIR)/skills ~/.config/opencode/skills
	ln -sf $(CURDIR)/commands ~/.config/opencode/commands

