.PHONY: lazyvim-configure
lazyvim-configure:
	ln -sf $(CURDIR)/lazyvim ~/.config/nvim

.PHONY: uninstall
uninstall:
	rm -rf ~/.config/nvim
	rm -rf ~/.local/share/nvim
	rm -rf ~/.local/state/nvim
	rm -rf ~/.cache/nvim

