.PHONY: configure
configure:
	rm -rfv ~/.i3
	mkdir -pv ~/.config/i3status
	ln -sf $(CURDIR)/i3status/config ~/.config/i3status/config
	mkdir -pv ~/.config/dunst
	ln -sf $(CURDIR)/dunst/dunstrc ~/.config/dunst/dunstrc
	mkdir -pv ~/.config/i3
	ln -sf $(CURDIR)/i3/config ~/.config/i3/config
