#!/bin/sh
# unslop.sh — comment-only view of a branch, and validated comment deletion.
#
#   unslop.sh scan  [-c N] [--all] [PATH...]                 comment lines only, with line numbers
#   unslop.sh prune [--dry-run] < plan                       delete/strip listed comment lines
#   unslop.sh check                                          prove only comments changed since scan
#   unslop.sh restore                                        undo everything back to the scan
#
# Plan lines are "path:lineno", one per line, as printed by scan.
# Deliberately no `set -e`: a failing `git symbolic-ref` must not kill the run silently.

CTX=3
ALL=0

die() { echo "$@" >&2; exit 1; }

# ---- scope ------------------------------------------------------------------
# A cached origin/HEAD keeps pointing at the old name forever after a default-branch rename, and
# `git fetch --prune` does not correct it. Verify before trusting it; only pay for a network round
# trip when it is actually stale. Never fall back to a local branch name: on a clone made before a
# master -> main rename that silently turns a one-file MR into a nine-file one.
resolve_base() {
  ref=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null) || ref=""
  if [ -n "$ref" ] && ! git rev-parse --verify --quiet "$ref^{commit}" >/dev/null; then
    git remote set-head origin --auto >/dev/null 2>&1
    ref=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null) || ref=""
  fi
  if [ -n "$ref" ] && git rev-parse --verify --quiet "$ref^{commit}" >/dev/null; then
    base=$ref
  else
    n=0; cands=""
    for c in origin/main origin/master origin/develop origin/trunk; do
      git rev-parse --verify --quiet "$c^{commit}" >/dev/null && { n=$((n+1)); cands="$cands $c"; base=$c; }
    done
    [ "$n" -eq 1 ] || {
      echo "SCOPE ERROR: cannot determine the base branch (candidates:${cands:- none})." >&2
      echo "  Ask the user which branch this MR targets. Edit nothing." >&2
      return 1
    }
    echo "SCOPE WARN: origin/HEAD was unusable; assuming $base." >&2
  fi
  mb=$(git merge-base HEAD "$base") || {
    echo "SCOPE ERROR: no merge base between HEAD and $base — unrelated histories, or a shallow" >&2
    echo "  clone (try git fetch --unshallow). Ask for an explicit base. Edit nothing." >&2
    return 1
  }
  echo "SCOPE: base=$base@$(git rev-parse --short "$base") merge-base=$(git rev-parse --short "$mb")"
}

# ---- language class ---------------------------------------------------------
classify() {
  case "$1" in
    *.go|*.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.java|*.kt|*.kts|*.scala|*.c|*.h|*.cc|*.cpp|*.hpp|*.cs|*.rs|*.swift|*.php|*.dart|*.css|*.scss|*.proto) echo c ;;
    *.py|*.pyi) echo py ;;
    *.sh|*.bash|*.zsh|*.rb|*.pl|*.yaml|*.yml|*.toml|*.tf|*.tfvars|*.nix|Dockerfile|*.dockerfile|Makefile|*.mk|*.cfg|*.ini|*.conf|*.gitignore) echo hash ;;
    *.sql|*.lua|*.hs|*.elm) echo dash ;;
    *.html|*.htm|*.xml|*.vue|*.svelte|*.md) echo xml ;;
    *.el|*.lisp|*.clj|*.cljs|*.edn) echo semi ;;
    *) echo "" ;;
  esac
}

# Edits are lost on regeneration, and the marker itself is matched by other tools.
is_generated() {
  case "$1" in
    vendor/*|*/vendor/*|node_modules/*|*/node_modules/*|dist/*|build/*|*/testdata/*) return 0 ;;
    *.pb.go|*_pb2.py|*_pb2.pyi|*_gen.go|*.gen.go|zz_generated*.go|*_string.go|mock_*.go|*_easyjson.go|*.min.js|*.min.css|*.lock|*.snap) return 0 ;;
    */migrations/*|migrations/*) return 0 ;;
  esac
  head -c 4096 "$1" 2>/dev/null | grep -qE '^(//|#|--|/\*) *(Code generated .* DO NOT EDIT|@generated|Autogenerated|AUTOGENERATED|DO NOT EDIT)' && return 0
  return 1
}

# ---- comment recogniser (shared by scan and prune) --------------------------
# Tracks /* */ and Python triple-quote state across the whole file, so continuation lines are
# recognised rather than guessed at. kind(): 0 = not a comment, 1 = whole line, 2 = trailing.
AWKLIB='
function quoted(s,   i, c, q) {
  q = 0
  for (i = 1; i <= length(s); i++) {
    c = substr(s, i, 1)
    if (c == "\\") { i++; continue }
    if (c == "\"" || c == "'"'"'" || c == "`") q = !q
  }
  return q
}
function trailing_at(line, mark,   p, off, pre) {
  off = 0
  while (1) {
    p = index(substr(line, off + 1), mark)
    if (p == 0) return 0
    p = p + off
    pre = substr(line, 1, p - 1)
    if (pre ~ /^[ \t]*$/) return 0                       # whole-line, handled elsewhere
    if (mark == "//" && substr(line, p - 1, 1) == ":") { off = p + 1; continue }   # scheme in a URL
    if (quoted(pre)) { off = p + 1; continue }           # marker sits inside a string literal
    return p
  }
}
function kind(line, class,   t) {
  t = line
  sub(/^[ \t]+/, "", t)
  if (class == "c") {
    if (inblock) { if (line ~ /\*\//) inblock = 0; return 1 }
    if (t ~ /^\/\*/) { if (line !~ /\*\//) inblock = 1; return 1 }
    if (t ~ /^\/\//) return 1
    if (line ~ /\/\*/ && line !~ /\*\//) inblock = 1
    return trailing_at(line, "//") ? 2 : 0
  }
  if (class == "py") {
    if (instr) { if (t ~ /("""|'"'"''"'"''"'"')/) instr = 0; return 1 }
    if (t ~ /^[rbfuRBFU]*("""|'"'"''"'"''"'"')/) {
      if (gsub(/"""/, "&", t) + gsub(/'"'"''"'"''"'"'/, "&", t) < 2) instr = 1
      return 1
    }
    if (t ~ /^#/) return (NR == 1 && t ~ /^#!/) ? 0 : 1
    return trailing_at(line, "#") ? 2 : 0
  }
  if (class == "hash") {
    if (t ~ /^#/) return (NR == 1 && t ~ /^#!/) ? 0 : 1
    return trailing_at(line, "#") ? 2 : 0
  }
  if (class == "dash") {
    if (t ~ /^--/) return 1
    return trailing_at(line, "--") ? 2 : 0
  }
  if (class == "xml") {
    if (inblock) { if (line ~ /-->/) inblock = 0; return 1 }
    if (t ~ /^<!--/) { if (line !~ /-->/) inblock = 1; return 1 }
    return 0
  }
  if (class == "semi") { return (t ~ /^;/) ? 1 : 0 }
  return 0
}
function is_directive(t) {
  # Gos own predicate (go/ast.isDirective): no space after //, none around the colon. Anchored on a
  # word boundary rather than line start so a trailing directive is recognised too.
  if (t ~ /(^|[ \t])\/\/(line |extern |export )/) return 1
  if (t ~ /(^|[ \t])\/\/[a-z0-9]+:[a-z0-9]/) return 1
  # Known exceptions that use the space form and must be matched by name.
  if (t ~ /(^|[ \t])\/\/ *(\+build|\+kubebuilder:|\+k8s:|swagger:)/) return 1
  if (t ~ /(^|[ \t])\/\/ *(eslint-|@ts-|prettier-ignore|biome-ignore|istanbul ignore|c8 ignore|v8 ignore|deno-lint-ignore|@jsx|@flow|\$FlowFixMe|source(Mapping)?URL=)/) return 1
  if (t ~ /(^|[ \t])\/\* *(eslint|global |prettier-ignore|istanbul ignore|@ts-|jshint|@license|@preserve)/) return 1
  if (t ~ /(^|[ \t])# *(noqa|type: *ignore|mypy:|ruff:|isort:|pragma: *no|fmt: *(on|off|skip)|yapf: *(disable|enable)|pylint:|pyright:|nosec|flake8:|shellcheck |-\*- *coding)/) return 1
  if (t ~ /(^|[ \t])-- *(noqa|sqlfluff)/) return 1
  if (t ~ /^#!/) return 1
  return 0
}
function tag(k, line,   s) {
  s = (k == 2) ? "   <TRAILING>" : ""
  if (is_directive(line)) s = s "   <DIRECTIVE>"
  if (line ~ /(TODO|FIXME|XXX|HACK)/) s = s "   <TODO>"
  if (line ~ /(Copyright|SPDX-License|@license)/) s = s "   <LICENCE>"
  return s
}
function in_ranges(n, ranges,   i, a, b, parts, se) {
  if (ranges == "") return 1
  i = split(ranges, parts, ",")
  for (a = 1; a <= i; a++) {
    split(parts[a], se, "-")
    if (n >= se[1] + 0 && n <= se[2] + 0) return 1
  }
  return 0
}
'

# ---- scan -------------------------------------------------------------------
# New-side line ranges the branch touched, widened by CTX so a comment sitting just above a changed
# statement is visible. A stale comment two lines from an edit is the common case.
hunk_ranges() {
  git diff -U0 "$1" -- "$2" | awk -v ctx="$CTX" '
    /^@@/ {
      match($0, /\+[0-9]+(,[0-9]+)?/)
      spec = substr($0, RSTART + 1, RLENGTH - 1)
      k = split(spec, p, ","); start = p[1] + 0; len = (k > 1) ? p[2] + 0 : 1
      if (len == 0) len = 1
      n++
      st[n] = start - ctx; if (st[n] < 1) st[n] = 1
      en[n] = start + len - 1 + ctx
    }
    END {
      # Widened windows overlap on adjacent hunks; merge so the header stays readable.
      for (i = 1; i <= n; i++)
        for (j = i + 1; j <= n; j++)
          if (st[j] < st[i]) { t = st[i]; st[i] = st[j]; st[j] = t; t = en[i]; en[i] = en[j]; en[j] = t }
      for (i = 1; i <= n; i++) {
        if (cs == "") { cs = st[i]; ce = en[i]; continue }
        if (st[i] <= ce + 1) { if (en[i] > ce) ce = en[i]; continue }
        out = out sep cs "-" ce; sep = ","; cs = st[i]; ce = en[i]
      }
      if (cs != "") out = out sep cs "-" ce
      print out
    }'
}

scan() {
  resolve_base || exit 1
  if [ $# -gt 0 ]; then
    # A named path is an explicit widening, so it counts even when untracked.
    files=$(git ls-files -- "$@"; git ls-files --others --exclude-standard -- "$@"; git diff --name-only --diff-filter=d "$mb" -- "$@")
    ALL=1
  else
    files=$(git diff --name-only --diff-filter=d "$mb")
  fi
  files=$(printf '%s\n' "$files" | sort -u | grep .)
  total=0; nfiles=0; skipped=""
  for f in $files; do
    [ -f "$f" ] || continue
    class=$(classify "$f")
    [ -n "$class" ] || { skipped="$skipped $f(ext)"; continue; }
    is_generated "$f" && { skipped="$skipped $f(generated)"; continue; }
    if [ "$ALL" = 1 ]; then ranges=""; else ranges=$(hunk_ranges "$mb" "$f"); fi
    out=$(awk -v class="$class" -v ranges="$ranges" "$AWKLIB"'
      { k = kind($0, class)
        if (k && in_ranges(NR, ranges)) printf "%6d| %s%s\n", NR, $0, tag(k, $0)
        n += (k && in_ranges(NR, ranges)) }
      END { if (n) print "COUNT " n > "/dev/stderr" }' "$f" 2>/tmp/unslop_count.$$)
    c=$(sed -n 's/^COUNT //p' /tmp/unslop_count.$$); rm -f /tmp/unslop_count.$$
    [ -n "$out" ] || continue
    nfiles=$((nfiles + 1)); total=$((total + ${c:-0}))
    snapshot "$f"
    echo "=== $f [$class] ${ranges:+lines $ranges}"
    echo "$out"
  done
  if [ "$nfiles" = 1 ]; then plural="file"; else plural="files"; fi
  echo "TOTALS: $total comment lines in $nfiles $plural"
  [ -n "$skipped" ] && echo "SKIPPED:$skipped"
  u=$(git ls-files --others --exclude-standard)
  if [ -n "$u" ]; then
    echo "UNTRACKED (absent from every git diff, not scanned — name one as a path to include it):"
    printf '%s\n' "$u"
  fi
  return 0
}

# ---- prune ------------------------------------------------------------------
# Refuses any line that is not a comment in that file's language, so a wrong line number cannot
# delete code. Whole-line comments are deleted; trailing ones are stripped back to the code.
prune() {
  plan=$(cat)
  [ -n "$plan" ] || die "prune: empty plan on stdin (expected path:lineno lines)"
  printf '%s\n' "$plan" | sed 's/:\([0-9]*\).*/ \1/' | sort -u -k1,1 -k2,2n | awk '{print $1}' | sort -u |
  while read -r f; do
    [ -f "$f" ] || die "prune: no such file: $f"
    class=$(classify "$f")
    [ -n "$class" ] || die "prune: unknown language for $f"
    snapshot "$f"
    nums=$(printf '%s\n' "$plan" | sed -n "s|^$f:\([0-9]*\).*|\1|p" | sort -un | tr '\n' ',')
    awk -v class="$class" -v targets="$nums" -v dry="$DRY" -v file="$f" "$AWKLIB"'
      BEGIN { split(targets, t, ","); for (i in t) if (t[i] != "") want[t[i] + 0] = 1 }
      { k = kind($0, class)
        if (!(NR in want)) {
          if (justdel && lastblank && $0 ~ /^[ \t]*$/) { justdel = 0; next }
          print > tmp; lastblank = ($0 ~ /^[ \t]*$/); if (!lastblank) justdel = 0; next
        }
        if (k == 0) { printf "PRUNE ERROR %s:%d is not a comment: %s\n", file, NR, $0 > "/dev/stderr"; bad = 1; print > tmp; next }
        if (k == 1) { printf "  -%s:%d %s\n", file, NR, $0 > "/dev/stderr"; justdel = 1; next }
        line = $0
        p = trailing_at(line, class == "c" ? "//" : (class == "dash" ? "--" : "#"))
        stripped = substr(line, 1, p - 1); sub(/[ \t]+$/, "", stripped)
        printf "  ~%s:%d %s\n", file, NR, stripped > "/dev/stderr"
        print stripped > tmp
      }
      END { if (bad) exit 3 }' tmp="$f.unslop.$$" "$f"
    st=$?
    if [ $st -ne 0 ]; then rm -f "$f.unslop.$$"; die "prune: aborted $f, nothing written"; fi
    if [ "$DRY" = 1 ]; then rm -f "$f.unslop.$$"; else mv "$f.unslop.$$" "$f"; fi
  done
}


# ---- snapshot / verify ------------------------------------------------------
# Lives under .git so it is never committed and never shows up in git status.
SNAP=$(git rev-parse --git-dir 2>/dev/null)/unslop-snapshot

snapshot() {
  d=$SNAP/$(dirname "$1")
  [ -f "$SNAP/$1" ] || { mkdir -p "$d" && cp "$1" "$SNAP/$1"; }
}

# The file with every comment removed and blank lines dropped: what must stay byte-identical.
skeleton() {
  awk -v class="$2" "$AWKLIB"'
    { k = kind($0, class)
      if (k == 1) next
      line = $0
      if (k == 2) {
        p = trailing_at(line, class == "c" ? "//" : (class == "dash" ? "--" : "#"))
        line = substr(line, 1, p - 1)
      }
      sub(/[ \t]+$/, "", line)
      if (line != "") print line
    }' "$1"
}

check() {
  [ -d "$SNAP" ] || die "check: no snapshot — run scan before editing"
  failmark=/tmp/unslop_fail.$$; rm -f "$failmark"
  (cd "$SNAP" && find . -type f) | sed 's|^\./||' | while read -r f; do
    [ -f "$f" ] || { echo "CHECK FAIL $f — file disappeared"; continue; }
    class=$(classify "$f")
    a=/tmp/unslop_a.$$; b=/tmp/unslop_b.$$
    skeleton "$SNAP/$f" "$class" > "$a"; skeleton "$f" "$class" > "$b"
    if cmp -s "$a" "$b"; then echo "CHECK OK   $f"
    else echo "CHECK FAIL $f — executable code changed:"; diff "$a" "$b" | head -20; : > "$failmark"; fi
    rm -f "$a" "$b"
  done
  if [ -f "$failmark" ]; then
    rm -f "$failmark"
    echo "CHECK: this pass changed executable code. Undo it with: unslop.sh restore"
    return 1
  fi
  return 0
}

restore() {
  [ -d "$SNAP" ] || die "restore: no snapshot"
  (cd "$SNAP" && find . -type f) | sed 's|^\./||' | while read -r f; do
    cp "$SNAP/$f" "$f" && echo "restored $f"
  done
}

# ---- main -------------------------------------------------------------------
cmd=$1; shift 2>/dev/null
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    -c) CTX=$2; shift 2 ;;
    --all) ALL=1; shift ;;
    --dry-run) DRY=1; shift ;;
    --) shift; break ;;
    -*) die "unknown flag: $1" ;;
    *) break ;;
  esac
done

case "$cmd" in
  scan) scan "$@" ;;
  prune) prune ;;
  check) check ;;
  restore) restore ;;
  *) die "usage: unslop.sh scan [-c N] [--all] [PATH...] | prune [--dry-run] < plan | check | restore" ;;
esac
