#!/bin/bash
# vim: tabstop=4 shiftwidth=4 noexpandtab
#
# xrandr scripts were generated by arandr

case "$1" in
    laptop)
        xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off --output HDMI-1-0 --off
        ;;
    home-dual)
        xrandr --output eDP-1 --mode 1920x1080 --pos 3440x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off --output HDMI-1-0 --primary --mode 3440x1440 --pos 0x0 --rotate normal
        ;;
    home-single)
        xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off --output HDMI-1-0 --primary --mode 3440x1440 --pos 0x0 --rotate normal
        ;;
    office-dual)
        xrandr --output eDP-1 --mode 1920x1080 --pos 0x360 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off --output HDMI-1-0 --off
        ;;
    office-single)
        xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off --output HDMI-1-0 --off
        ;;
    *)
        echo "Usage: $0 {laptop|home-single|home-dual|office-single|office-dual}"
        exit 2
esac


# post switch
sleep 3

nitrogen --restore

# keyboard over USB-C is always loose settings on plug/unplug
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:caps,caps:escape us,ru

exit 0

