.PHONY: configure
configure:
	ln -sf $(CURDIR)/config ~/.config/bat/config
	mkdir -p ~/.config/bat/themes
	ln -sf $(CURDIR)/themes/Vesper.tmTheme ~/.config/bat/themes/Vesper.tmTheme
	bat cache --build

