.PHONY: configure
configure:
	mkdir -pv ~/.config/alacritty
	ln -sf $(CURDIR)/alacritty.toml ~/.config/alacritty/alacritty.toml
	ln -sf $(CURDIR)/catppuccin-macchiato.toml ~/.config/alacritty/catppuccin-macchiato.toml

