.PHONY: configure
configure:
	mkdir -pv ~/.config/alacritty/themes
	ln -sf $(CURDIR)/alacritty.yml ~/.config/alacritty/alacritty.yml
	git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

