source ~/.zsh.d/themes/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

ZSH_CUSTOM=~/.zsh.d

for config_file ("$ZSH_CUSTOM"/*.zsh(N)); do
  source "$config_file"
done
unset config_file

# Save a ton of history
export HISTSIZE=50000000
export HISTFILESIZE=$HISTSIZE;
HIST_STAMPS="yyyy-mm-dd"
# Ignore basic commands
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help:.."
# Share history between active sessions
setopt share_history
# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

# Never know when you're gonna need to popd!
setopt AUTO_PUSHD

# Disable "zsh: no matches found"
setopt no_nomatch

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH"

# Editor
export EDITOR='vim'

