# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh configuration.
ZSH="$HOME/.oh-my-zsh"

# awesome dark theme borrowed from https://github.com/mitsuhiko/dotfiles/tree/master/zsh/custom/themes
ZSH_THEME="powerlevel10k/powerlevel10k"
#ZSH_THEME="mitsuhiko"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=30

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(git osx node npm brew)
plugins=(git-prompt macos z extract gnu-utils virtualenv docker docker-compose)

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.zsh.d

# Save a ton of history
export HISTSIZE=50000000
export HISTFILESIZE=$HISTSIZE;
# Share history between bash and zsh
HISTFILE=~/.bash_history
HIST_STAMPS="yyyy-mm-dd"
# Ignore basic commands
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help:.."

# Never know when you're gonna need to popd!
setopt AUTO_PUSHD

# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

# Show contents of directory after cd-ing into it
#chpwd() {
    #ls -lrthG
#}

source "$ZSH/oh-my-zsh.sh"
unsetopt share_history
unsetopt extended_history
setopt no_nomatch

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

autoload -Uz zcalc

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH"

# Editor
export EDITOR='vim'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# If iTerm is detected these themes are used for regular windows
# and ssh respectively
ITERM_NORMAL_PROFILE='Fancy'
ITERM_SSH_PROFILE='FancySSH'

# On iTerm we switch terminals for SSH if we have it.  This switches to
# the SSH profile and back when ssh is run from the terminal.
if [[ "$TERM_PROGRAM" == iTerm.app ]]; then
  function ssh() {
    echo -n -e $'\033]50;SetProfile='$ITERM_SSH_PROFILE'\a'
    command ssh "$@"
    echo -n -e $'\033]50;SetProfile='$ITERM_NORMAL_PROFILE'\a'
  }
fi

