# Path to your oh-my-zsh configuration.
ZSH="$HOME/.oh-my-zsh"

# https://github.com/mitsuhiko/dotfiles/tree/master/zsh/custom/themes
ZSH_THEME="mitsuhiko"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(git osx node npm brew)
plugins=(git-prompt osx z extract gnu-utils)

source "$ZSH/oh-my-zsh.sh"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=~/.zsh-custom

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
HIST_STAMPS="yyyy-mm-dd"
SAVEHIST=20000

# Never know when you're gonna need to popd!
setopt AUTO_PUSHD

# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

# Show contents of directory after cd-ing into it
#chpwd() {
#    ls -lrthG
#}

unsetopt share_history

alias g="git"

export GOROOT=/opt/google/golang/1.8.1
export GOPATH=~/Projects
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

