# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Store multiline cmds as single
shopt -s cmdhist

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# append to the history file, don't overwrite it
shopt -s histappend

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Do not autocomplete when accidentally pressing Tab on an empty line. (It takes
# forever and yields "Display all 15 gazillion possibilites?")
shopt -s no_empty_cmd_completion;

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
export LC_CTYPE="en_US.UTF-8"

# Autocompletion
complete -d cd pushd rmdir;
complete -u finger mail;
complete -v set unset;

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# default project folder name.
export PROJECTS=$HOME/Projects
if [[ ! -d $PROJECTS ]]; then
    mkdir $PROJECTS
fi

# load all the aliases or functions when you starts bash.
# to see all aliases, type alias.
# to see all functions, type declare -f.
#
# to add a new alias/functions,
# 1. create a new filename in ~/.bash.d/name_of_the_category.sh
# 2. add your own aliases or functions and save the file
# 3. reload bash by typing source .bashrc
if [ -d ~/.bash.d ]; then
  for f in ~/.bash.d/*.sh; do
    if [ -r $f ]; then
      source $f
    fi
  done
  unset f
fi
