# Load ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/.{extra,bash_prompt,exports,aliases,functions}; do
    [ -r "$file" ] && source "$file"
done
unset file

# init z - https://github.com/rupa/z
. ~/bin/z/z.sh

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
export LC_CTYPE="en_US.UTF-8"

# Autocompletion
complete -d cd pushd rmdir;
complete -u finger mail;
complete -v set unset;

# Enable bash autocompletion
[ -f /etc/bash_completion ] && . /etc/bash_completion

# Enable custom autocompletion
[ -d ~/.bash/completion ] && for file in ~/.bash/completion/*; do
    [ -f "$file" ] && source "$file";
done;
unset file;

# Enable completions from homebrew
if [ `type -t brew` > /dev/null ] && [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Git stuff
# @todo: move to ~/.bash/completion/git
[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash;
[ -f ~/.git-prompt.sh ] && source ~/.git-prompt.sh;

# Load bash_extra
[ -f .bash_extra ] && . .bash_extra

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Do not autocomplete when accidentally pressing Tab on an empty line. (It takes
# forever and yields "Display all 15 gazillion possibilites?")
shopt -s no_empty_cmd_completion;

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
